export {HomePage} from "./HomePage"
export {LoginPage} from "./LoginPage"
export {RegisterPage} from "./RegisterPage"
export {ProductFormPage} from "./ProductFormPage"
export {CategoryProductPage} from "./CategoryProductPage" 
export {SingleProductPage} from "./SingleProductPage"